### ISSUE TITLE
Can not start service

### ISSUE THREAD

**Issue by alicimertcan** [SitinCloud/Owlyshield#11]
Hello,

I have installed the project however whenever I start the owlyshield_ransom.exe I am getting the following error.

Error: Winapi(Os { code: 1063, kind: Uncategorized, message: "The service process could not connect to the service controller." })

The driver has been installed successfully, but the OwlyShield Service is not running and I am getting error when I try to start: error 1068 the dependency service or group failed to start.

**Comment by dlescos** [comment]
I'm not able to reproduce it. Do you have an error in the Event Viewer >> Applications, with source "Owlyshield Ransom Rust"?

**Comment by dlescos** [comment]
Hi,

I think you may miss the MS c++ redistributables dependencies :
https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
