### ISSUE TITLE
`try_kill` does not terminate the given PID

### ISSUE THREAD

**Issue by sn99** [SitinCloud/Owlyshield#14]
I am trying to port the minifilter and `driver_com` to my own personal project [minifilter-rs](https://github.com/sn99/minifilter-rs) with updated windows-rs/windows_sys. I am able to register rust program to the minifilter but am unable to kill the process with the given PID.

The error I receive is `0xC0000066` aka `0xC0000066 	0x00000527 	NT_STATUS_NO_SUCH_GROUP 	“The specified group does not exist.”` 

Is this supposed to happen?

**Comment by dlescos** [comment]
I remember we had issue debugging this part. Ultimately we decided to kill them from user space from session 0 (service).

**Comment by sn99** [comment]
Ah okay, do you think it is worth to invest time again to solve it? If it is I might give it a go

**Comment by dlescos** [comment]
I close it due to inactivity. Will reopen it if needed.

**Comment by Siradankullanici** [comment]
> Probably a good thing to be able to kill it from kernel space. I can't think of a scenario a malware with admin rights could escape from a user-space kill command but we never know...
> 
> So you will be welcome if you want to have a look at this issue :)

 Not really...
