### ISSUE TITLE
Heavy processor usage

### ISSUE THREAD

**Issue by pierreroger6466** [SitinCloud/Owlyshield#20]
I have noticed a frequent high level processor usage (up to 20%) associated with up to 200 Mb memory usage. Then both measures decrease to 3% and less than 40 Mb and the phenomenon resumes.

**Comment by dlescos** [comment]
It seems we have to enhance `process:ProcessRecord::is_to_cluster`. Most clustering operations last 50 to 500µs (excluding process spawning time). In case there is a high activity, they are repeated each 500µs to 5s, which is to frequent.
