### ISSUE TITLE
A few diskwipers and MBR lockers reported undetected

### ISSUE THREAD

**Issue by pierreroger6466** [SitinCloud/Owlyshield#26]
Although I know it is not the prime target of Owlyshield I create the issue on behalf of a user from malwaretips.com regarding wipers or MBR lockers.

**Comment by dlescos** [comment]
MBR lockers are out of scope. We were able to detect Hermetic Wiper because it was not only a MBR locker.

**Comment by dlescos** [comment]
Closing it as out of scope.
