### ISSUE TITLE
crash during the day with non understable reason (for me)

### ISSUE THREAD

**Issue by pierreroger6466** [SitinCloud/Owlyshield#27]
Nom de l’application défaillante owlyshield_ransom.exe, version : 0.0.0.0, horodatage : 0x631a4db3
Nom du module défaillant : ntdll.dll, version : 10.0.19041.1806, horodatage : 0x1000a5b9
Code d’exception : 0xc0000005
Décalage d’erreur : 0x0000000000016544
ID du processus défaillant : 0x2fa4
Heure de début de l’application défaillante : 0x01d8c450f40708f7
Chemin d’accès de l’application défaillante : C:\Program Files\Owlyshield Ransom Community\Owlyshield Service\owlyshield_ransom.exe
Chemin d’accès du module défaillant: C:\WINDOWS\SYSTEM32\ntdll.dll
ID de rapport : 3a5438a0-a55b-42a5-9883-f6598211da92
Nom complet du package défaillant : 
ID de l’application relative au package défaillant : 

Détecteur d'erreurs , type 0
Nom d’événement : APPCRASH
Réponse : Non disponible
ID de CAB : 0

Signature du problème : 
P1 : owlyshield_ransom.exe
P2 : 0.0.0.0
P3 : 631a4db3
P4 : ntdll.dll
P5 : 10.0.19041.1806
P6 : 1000a5b9
P7 : c0000005
P8 : 0000000000016544
P9 : 
P10 :

**Comment by dlescos** [comment]
Do you see something in the event viewer (filter on "Owlyshield" in the *Application* chapter)?

**Comment by pierreroger6466** [comment]
Nothing more. Only this message showing up very often:
Le filtre de système de fichiers « OwlyshieldRansomFilter » (Version 10.0, ‎2021‎-‎06‎-‎21T17:44:34.000000000Z) n’a pas réussi à s’attacher au volume « \Device\Harddisk0\DR0 ». Le filtre a renvoyé un état final non standard 0xC0000034. Ce filtre et/ou les applications qui le prennent en charge doivent gérer cette condition. Si cette condition persiste, contactez le fournisseur.

**Comment by pierreroger6466** [comment]
It seems it didn't start this morning maybe the deferred service start should be changed to immediate.

**Comment by pierreroger6466** [comment]
I had a crash this morning with these two messages:
"Critical error: panicked at 'Cannot send iomsg', src\main.rs:297:29"

Followed by:

"Critical error: panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src\worker.rs:295:60"

It was 2 hours after I started working with nothing obvious to be noted.

**Comment by pierreroger6466** [comment]
Since 2 days there are no more crashes so I can say that the issue seems very difficult to reproduce. Therefore I close it and will reopen an new one if the problem comes back again.
