### ISSUE TITLE
Installation error on windows 7 SP1

### ISSUE THREAD

**Issue by solderzzc** [SitinCloud/Owlyshield#29]
I tried to install Owlyshield, it reported `windows requires a digitally signed driver` error.
![Screenshot 2022-09-19 111804](https://user-images.githubusercontent.com/3085564/191087792-84ed5ebe-fc2e-4e47-b900-1d7a5cca0663.png)

**Comment by dlescos** [comment]
Hi,

We did not test it on windows 7 but it might work.

Could you check the properties of `C:\Windows\System32\drivers\OwlyshieldRansomFilter.sys` ? In the "Digital Signatures" section, you should see something like this:
![image](https://user-images.githubusercontent.com/66389253/191097488-2975e645-d403-49b7-a462-556193dbdd24.png)

Is seems Microsoft issued this root certificate in 2014. Is your instance last update older?

**Comment by solderzzc** [comment]
It's same as the screen you captured, the windows 7 is a sandbox system we have for ransomware analysis, I'll apply updates to the machine for the CA cert expire issue.

**Comment by solderzzc** [comment]
I upgraded the windows 7 with latest patches, then I uninstalled Owlyshield and rebooted windows 7. I installed Owlyshield again, there was no driver error message this time, but when I load owlyshield_ransom.exe, there was another 'could not connect to the service controller`.
![Screenshot 2022-09-19 151134](https://user-images.githubusercontent.com/3085564/191128990-e2e8aa43-77f4-4579-b904-27f79b55616b.png)

**Comment by solderzzc** [comment]
I also tried to run it on Windows 10, it also had the same error `Error: Winapi(OS code: 1063, kind: Uncategorized, Message:" The service process could not connect to the service controller."})`

**Comment by dlescos** [comment]
Hi,

It's a service (unless you explicitly compile it with particular flags). Try to start the "Owlyshield Service".

**Comment by dlescos** [comment]
I close it due to inactivity. Feel free to reopen it if necessary.
