### ISSUE TITLE
Error message in Windows 11 event viewer

### ISSUE THREAD

**Issue by pierreroger6466** [SitinCloud/Owlyshield#33]
Le certificat reçu du serveur distant est arrivé à expiration ou n’est pas encore valide. Échec de la demande de connexion TLS. Les données associées contiennent le certificat de serveur. 
 le processus client SSPI est owlyshield_ransom (PID : 6212).

**Comment by dlescos** [comment]
Certificate for api.owlyshield.com has been renewed.
