### ISSUE TITLE
Microsoft Defender malware notification regarding Owlyshield_Ransom.exe

### ISSUE THREAD

**Issue by pierreroger6466** [SitinCloud/Owlyshield#6]
![image (1)](https://user-images.githubusercontent.com/92184062/143884152-94bf7966-6b99-4815-820d-ce0a1de6fb90.png)

**Comment by pierreroger6466** [comment]
Looks like a false positive in Microsoft Defender.

**Comment by dlescos** [comment]
Microsoft is [not clear about it](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Program:Win32/Contebrew.A!ml). That's clearly a false positive.

Others projects seem to [present this issue too](https://github.com/danielkrupinski/Osiris/issues/2786). It might be solved by signing owlyshield.exe but I'm very unsure about it.

We may consider to add an exclusion at this installation if this issue becomes recurrent.
